# -*- coding: utf-8 -*-
"""IMG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iIxClc2BwRBE74hCL9lVd0c5RZUvcWkd
"""

!pip install imageai

!pip install --upgrade tensorflow

from imageai.Detection import *
import os

exe_path = os.getcwd()
detect = ObjectDetection()

detect.setModelTypeAsRetinaNet()

detect.setModelPath(os.path.join(exe_path, "/content/drive/MyDrive/CGCP14/resnet50_coco_best_v2.1.0.h5"))
detect.loadModel()

detections = detect.detectObjectsFromImage(input_image=os.path.join(exe_path, "/content/sample_data/1.jpg"), output_image_path=os.path.join(exe_path, "/content/sample_data/out.jpg"))

for eachObject in detections:
  print(eachObject["name"], " : ", eachObject["percentage_probability"])

from IPython.display import Image
print("Output Image")
Image("/content/sample_data/out.jpg", width=600, height=450)

