# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZae05_O1_oIZ9ntYJuWLnttN8HPglQE
"""

!pip install pytesseract
!sudo apt install tesseract-ocr

import pytesseract
from PIL import Image

# Load image
img = Image.open('/content/sample_data/image.JPG')

# Perform OCR using pytesseract
text = pytesseract.image_to_string(img)

# Print the text
print(text)