# -*- coding: utf-8 -*-
"""pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2Sxi9reI6VU64jZ3nDbRbk1naJ7OpdN
"""

pip install pyPDF2

from PyPDF2 import PdfReader

reader = PdfReader('/content/sample_data/Resume.pdf')

page = reader.pages[0]

text = page.extract_text()
print(text)