# -*- coding: utf-8 -*-
"""xlsx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhN2a0ZKyzczCQOiDRL5sBUsfIbRCHhS
"""

!pip install openpyxl

"""# **Opening File**"""

from openpyxl import load_workbook

data_file = '/Sample_Retailer_Data.xlsx'

# Load the entire workbook.
wb = load_workbook(data_file)

# List all the sheets in the file.
print("Found the following worksheets:")
for sheetname in wb.sheetnames:
    print(sheetname)

"""# **Accesing Data from Worksheet**"""

from openpyxl import load_workbook

data_file = '/Sample_Retailer_Data.xlsx'

# Load the entire workbook.
wb = load_workbook(data_file)

# Load one worksheet.
ws = wb['Sample+-+Retailer+Data']
all_rows = list(ws.rows)

print(f"Found {len(all_rows)} rows of data.")

print("\nFirst rows of data:")
for row in all_rows[:5]:
    print(row)

"""# **Accesing Data From Cells**"""

from openpyxl import load_workbook

data_file = '/Sample_Retailer_Data.xlsx'

# Load the entire workbook.
wb = load_workbook(data_file)

# Load one worksheet.
ws = wb['Sample+-+Retailer+Data']
all_rows = list(ws.rows)

for cell in all_rows[0]:
    print(cell.value)

"""# **Data From Desired Cell/Cells**"""

from openpyxl import load_workbook

data_file = '/Sample_Retailer_Data.xlsx'

# Load the entire workbook.
wb = load_workbook(data_file, data_only=True)

# Load one worksheet.
ws = wb['Sample+-+Retailer+Data']
all_rows = list(ws.rows)

# Pull information from specific cells.
for row in all_rows[1:52]:
    Sales = row[0].value
    Profit = row[3].value
    Discount = row[4].value

    print(f"{Sales}")
    print(f" {Profit}% of profit in sales")
    print(f" {Discount}% Discount given to Coustmer")